CREATE TABLE "role" (
  "role_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" varchar(200)
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" bigint NOT NULL,
  "name" varchar(120) NOT NULL,
  "username" varchar(80) UNIQUE NOT NULL,
  "email" varchar(150) UNIQUE,
  "password_hash" varchar(255) NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "last_login_at" timestamp,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "category" (
  "category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" varchar(200),
  "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "unit_of_measure" (
  "unit_of_measure_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "abbreviation" varchar(10) UNIQUE NOT NULL,
  "type" varchar(30) NOT NULL,
  "conversion_factor" decimal(15,6) NOT NULL
);

CREATE TABLE "product" (
  "product_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint NOT NULL,
  "base_unit_id" bigint NOT NULL,
  "name" varchar(150) NOT NULL,
  "description" varchar(300),
  "barcode" varchar(100) UNIQUE,
  "sale_price" decimal(12,2) NOT NULL,
  "min_stock" decimal(15,3) NOT NULL DEFAULT 0,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "promotion" (
  "promotion_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "unit_of_measure_id" bigint NOT NULL,
  "name" varchar(150),
  "promotion_quantity" decimal(15,3) NOT NULL,
  "promotional_price" decimal(12,2) NOT NULL,
  "repeatable" boolean NOT NULL DEFAULT true,
  "start_date" timestamp,
  "end_date" timestamp,
  "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "supplier" (
  "supplier_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "document_number" varchar(20),
  "phone" varchar(30),
  "type" varchar(30),
  "contact_name" varchar(150),
  "address" varchar(250),
  "notes" varchar(500),
  "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "purchase" (
  "purchase_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" bigint,
  "user_id" bigint NOT NULL,
  "purchase_date" timestamp NOT NULL,
  "subtotal" decimal(12,2) NOT NULL,
  "total" decimal(12,2) NOT NULL,
  "status" varchar(30) NOT NULL,
  "notes" varchar(500)
);

CREATE TABLE "purchase_detail" (
  "purchase_detail_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "unit_of_measure_id" bigint NOT NULL,
  "quantity" decimal(15,3) NOT NULL,
  "base_quantity" decimal(15,3) NOT NULL,
  "unit_cost" decimal(12,4) NOT NULL,
  "subtotal" decimal(12,2) NOT NULL
);

CREATE TABLE "lot" (
  "lot_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "purchase_detail_id" bigint NOT NULL,
  "lot_code" varchar(100),
  "entry_date" timestamp NOT NULL,
  "expiration_date" date
);

CREATE TABLE "sale" (
  "sale_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "sale_date" timestamp NOT NULL,
  "subtotal" decimal(12,2) NOT NULL,
  "discount" decimal(12,2) NOT NULL DEFAULT 0,
  "total" decimal(12,2) NOT NULL,
  "payment_method" varchar(30),
  "status" varchar(30) NOT NULL,
  "cancellation_reason" varchar(500),
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "sale_detail" (
  "sale_detail_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sale_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "unit_of_measure_id" bigint NOT NULL,
  "quantity" decimal(15,3) NOT NULL,
  "base_quantity" decimal(15,3) NOT NULL,
  "unit_price" decimal(12,4) NOT NULL,
  "discount" decimal(12,2) NOT NULL DEFAULT 0,
  "subtotal" decimal(12,2) NOT NULL
);

CREATE TABLE "internal_consumption" (
  "internal_consumption_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "consumption_date" timestamp NOT NULL,
  "reason" varchar(300),
  "notes" varchar(500)
);

CREATE TABLE "internal_consumption_detail" (
  "internal_consumption_detail_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "internal_consumption_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "unit_of_measure_id" bigint NOT NULL,
  "quantity" decimal(15,3) NOT NULL,
  "base_quantity" decimal(15,3) NOT NULL
);

CREATE TABLE "inventory_movement" (
  "inventory_movement_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "lot_id" bigint,
  "user_id" bigint NOT NULL,
  "movement_type" varchar(40) NOT NULL,
  "base_quantity" decimal(15,3) NOT NULL,
  "purchase_detail_id" bigint,
  "sale_detail_id" bigint,
  "internal_consumption_detail_id" bigint,
  "movement_date" timestamp NOT NULL,
  "reason" varchar(150),
  "notes" varchar(500)
);

CREATE TABLE "sale_history" (
  "sale_history_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sale_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "action" varchar(30) NOT NULL,
  "previous_data" json,
  "new_data" json,
  "reason" varchar(500),
  "created_at" timestamp NOT NULL
);

CREATE TABLE "shopping_list" (
  "shopping_list_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL,
  "source" varchar(30) NOT NULL,
  "status" varchar(30) NOT NULL,
  "estimated_cost" decimal(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE "shopping_list_detail" (
  "shopping_list_detail_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shopping_list_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "supplier_id" bigint,
  "unit_of_measure_id" bigint NOT NULL,
  "suggested_quantity" decimal(15,3) NOT NULL,
  "purchased_quantity" decimal(15,3) NOT NULL DEFAULT 0,
  "estimated_cost" decimal(12,2) NOT NULL DEFAULT 0,
  "purchased" boolean NOT NULL DEFAULT false
);

CREATE TABLE "business_settings" (
  "business_settings_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_name" varchar(150) NOT NULL,
  "ruc" varchar(20),
  "address" varchar(250),
  "phone" varchar(30),
  "currency" varchar(10) NOT NULL DEFAULT 'PEN',
  "logo_url" varchar(500),
  "default_min_stock" decimal(15,3) NOT NULL DEFAULT 10,
  "expiration_warning_days" int NOT NULL DEFAULT 10,
  "critical_stock_alert" boolean NOT NULL DEFAULT true,
  "expiration_alert" boolean NOT NULL DEFAULT true,
  "auto_print_ticket" boolean NOT NULL DEFAULT false,
  "updated_at" timestamp
);

CREATE INDEX ON "product" ("name");

CREATE INDEX ON "lot" ("product_id", "expiration_date");

CREATE INDEX ON "inventory_movement" ("product_id", "movement_date");

CREATE INDEX ON "inventory_movement" ("lot_id", "movement_date");

CREATE INDEX ON "inventory_movement" ("movement_type");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("role_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product" ADD FOREIGN KEY ("base_unit_id") REFERENCES "unit_of_measure" ("unit_of_measure_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "promotion" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "promotion" ADD FOREIGN KEY ("unit_of_measure_id") REFERENCES "unit_of_measure" ("unit_of_measure_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase" ADD FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("supplier_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_detail" ADD FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("purchase_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_detail" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_detail" ADD FOREIGN KEY ("unit_of_measure_id") REFERENCES "unit_of_measure" ("unit_of_measure_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lot" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lot" ADD FOREIGN KEY ("purchase_detail_id") REFERENCES "purchase_detail" ("purchase_detail_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_detail" ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("sale_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_detail" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_detail" ADD FOREIGN KEY ("unit_of_measure_id") REFERENCES "unit_of_measure" ("unit_of_measure_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "internal_consumption" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "internal_consumption_detail" ADD FOREIGN KEY ("internal_consumption_id") REFERENCES "internal_consumption" ("internal_consumption_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "internal_consumption_detail" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "internal_consumption_detail" ADD FOREIGN KEY ("unit_of_measure_id") REFERENCES "unit_of_measure" ("unit_of_measure_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement" ADD FOREIGN KEY ("lot_id") REFERENCES "lot" ("lot_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement" ADD FOREIGN KEY ("purchase_detail_id") REFERENCES "purchase_detail" ("purchase_detail_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement" ADD FOREIGN KEY ("sale_detail_id") REFERENCES "sale_detail" ("sale_detail_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement" ADD FOREIGN KEY ("internal_consumption_detail_id") REFERENCES "internal_consumption_detail" ("internal_consumption_detail_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_history" ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("sale_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list_detail" ADD FOREIGN KEY ("shopping_list_id") REFERENCES "shopping_list" ("shopping_list_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list_detail" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list_detail" ADD FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("supplier_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list_detail" ADD FOREIGN KEY ("unit_of_measure_id") REFERENCES "unit_of_measure" ("unit_of_measure_id") DEFERRABLE INITIALLY IMMEDIATE;
